### ISSUE TITLE
separated token schemes

### ISSUE THREAD

**Issue by floodico** [ueberauth/guardian_db#100]
Hey! 
I want to have several different types of tokens in different schemes and manage them at the context level. But if I understand correctly, guardian provides [api](https://github.com/ueberauth/guardian_db/blob/master/lib/guardian/db.ex), where we can't pass another token model(some module that inherited from default Token model). Right? 
It looks very not flexible

**Comment by hassox** [comment]
I'm not quite sure I know what you mean here. Can you maybe give an example of what you're trying to do?

**Comment by floodico** [comment]
hi @hassox! i mean i need to create for example *user_tokens* scheme, *qr_code_tokens* scheme and some *invite_tokens* scheme. But as i see, GuardianDB can work only for the one scheme

**Comment by yordis** [comment]
@floodico could you share some use cases that will require this to be implemented?

**Comment by yordis** [comment]
Due to inactivity I will close this issue, feel free to open it again if your issue persists. In terms of having multiple schemas, create on your application business rules the join tables.
