### ISSUE TITLE
Revoking Token thats already been removed throws error rather than returning error

### ISSUE THREAD

**Issue by rraub** [ueberauth/guardian_db#102]
We've run into a condition where a request to refresh a token was replayed which resulted in duplicate requests processed at the same time. The first one succeeded and the second one failed with an `Ecto.StaleEntryError` when trying to revoke and delete the token.  Instead of doing a [delete on the Model](https://github.com/ueberauth/guardian_db/blob/f5fec0496679eb672e479471c404bf79ddd57761/lib/guardian/db.ex#L175) could we just do a delete by the value of the primary key so we can return an `{:error}` instead of throwing an error?   
Similar to: https://github.com/ueberauth/guardian_db/blob/82fb31f84da639d5a43cf698224458bc14289232/lib/guardian/db/token.ex#L66

**Comment by yordis** [comment]
@rraub would you mind to open a PR with the desired behavior?
