### ISSUE TITLE
Changelog updates since 0.8

### ISSUE THREAD

**Issue by brianbowden** [ueberauth/guardian_db#107]
Would it be possible to update the CHANGELOG for updates since 0.8? 

Thanks!

**Comment by yordis** [comment]
Some of the changes are in the actually release 😭 

Thank you for the feedback

**Comment by brianbowden** [comment]
😭 Oh okay, thanks! 😂

**Comment by yordis** [comment]
Feel free to open a PR adding the changelog updates, I am not sure what is the value-added at this point.
