### ISSUE TITLE
Update `guardian_db` to be compatible with `guardian` base

### ISSUE THREAD

**Issue by wende** [ueberauth/guardian_db#11]
Right now `guardian` is at 0.10.1 while `guardian_db` works only with `0.9.0`

**Comment by hassox** [comment]
Thanks. Updated.

**Comment by combsco** [comment]
FYI: https://hex.pm/packages/guardian_db
Is still saying Guardian 0.9 is what has to be installed to use Guardian_DB

**Comment by wende** [comment]
@hassox  I don't see that updated. 0.4.0 still requires Guardian 0.9 as @combsco says.
Am I doing something wrong?
