### ISSUE TITLE
Compatibility with Guardian 2.0

### ISSUE THREAD

**Issue by IvanShpotenko** [ueberauth/guardian_db#110]
It seems like Guardian goes 2.0. Does anyone know if guardian 2.0 has any breaking changes that would require updating guardian_db to be compatible?

```
Failed to use "guardian" (version 2.0.0) because
  guardian_db (version 2.0.1) requires ~> 1.0
  mix.exs specifies ~> 2.0
```

**Comment by yordis** [comment]
@IvanShpotenko yeah totally, let me release a new version, the breaking change was due to removing Phoenix specific code.

Feel free to use `v2` without any worry about `guardian_db`

**Comment by yordis** [comment]
@IvanShpotenko new version released, it should work now.
