### ISSUE TITLE
Do not fix ecto version

### ISSUE THREAD

**Issue by dolfinus** [ueberauth/guardian_db#117]
Hello.

I've tried to update dependencies of my project, but got this error:
```
* ecto (Hex package)
  the dependency ecto 3.4.5

  > In deps/guardian_db/mix.exs:
    {:ecto, "~> 3.0", [env: :prod, hex: "ecto", repo: "hexpm", optional: false]}

  does not match the requirement specified

  > In deps/ecto_sql/mix.exs:
    {:ecto, "~> 3.5.0", [env: :prod, hex: "ecto", repo: "hexpm", optional: false]}
```

Can you please replace `~> 3.0` with `>= 3.0` for ecto and ecto_sql dependencies?
Current deps specification is too strict.

**Comment by Hanspagh** [comment]
Hi @dolfinus 

In elixir, ~> 3.0 translates to >= 3.0.0 and < 4.0.0, so I am not quite sure what is happening here 
https://hexdocs.pm/elixir/Version.html

Which packages are you trying to install?

**Comment by dolfinus** [comment]
Sorry, my fault. The issue was caused by another package which was mentioned only in the end of log, and I've missed it.
