### ISSUE TITLE
cut a new release?

### ISSUE THREAD

**Issue by mayoms** [ueberauth/guardian_db#134]
👋 

I was attempting to implement the adapter behaviour described in your docs, and was warned that such a behaviour and spec did not exist. 

Looks like the last release was in 2020. Given that folks seem to be using the adapter spec, are there any plans to cut a release?

**Comment by yordis** [comment]
We have a PR related to the Storage, and an open related to the refactored done #131 

I will suggest subscribing to Release notifications, and/or contributing to the reminding work.
