### ISSUE TITLE
Ecto 2.0

### ISSUE THREAD

**Issue by talklittle** [ueberauth/guardian_db#16]
Simply updating the dependency to `{:ecto, "~> 2.0.0-rc"}` seems to compile fine.

Maybe needs a few additional config changes for tests, based on the migration instructions at http://blog.plataformatec.com.br/2016/04/ecto-2-0-0-rc-is-out

**Comment by doomspork** [comment]
Awesome @talklittle!  Are you going to get started on a pull request? 😀 This would be great to have when Ecto 2.0 ships 👍

**Comment by talklittle** [comment]
I'll try to get it working. Currently `mix test` is failing with badmatch `{:error, :already_up}`, but that seems to happen on `master` as well. Hopefully Ecto 2.0's test improvements help avoid this kind of error.
