### ISSUE TITLE
Handle expired tokens at guardian_db itself

### ISSUE THREAD

**Issue by chvanikoff** [ueberauth/guardian_db#18]
Hi,
How about adding some (1:100 for example) probability of running `purge_expired_tokens!` from `create!` function? Probably add config option `autocleanup` which is false by default (for those who want to implement or already have implemented some specific GC algorithms).
That's how a lot of software does GC jobs and would be helpful to have here as well I think.
Something like

``` elixir
def create!(claims, jwt) do
  if Dict.get(Application.get_env(:guardian_db, GuardianDb), :autoremove, false) and :random.uniform() >= 0.99 do
    purge_expired_tokens!
  end
  prepared_claims = claims |> Dict.put("jwt", jwt) |> Dict.put("claims", claims)
  GuardianDb.repo.insert cast(%Token{}, prepared_claims, [], [:jti, :typ, :aud, :iss, :sub, :exp, :jwt, :claims])
end
```

**Comment by hassox** [comment]
Interesting approach. I was thinking about purging the other day. My initial thoughts were to setup a supervisor that runs on a timer and just periodically cleans it outside of all requests. Thoughts?

**Comment by chvanikoff** [comment]
@hassox it sounds like a better solution but I think it would be an overhead for such a simple task. It is worth nothing to add these 3 lines and update documentation with this config key description, unlike creating a GC server. You can always add GC worker later but for now this probability-based GC will work just fine for most of users I believe.

**Comment by hassox** [comment]
I've just added a worker that you can optionally add to your supervision tree @chvanikoff. https://github.com/hassox/guardian_db/pull/20 Love some feedback.

**Comment by chvanikoff** [comment]
@hassox Generally, it's ok. But here is what I'd change:
1. Move `interval` to config and have some reasonable default value (30m for example)
2. Use minutes rather than milliseconds. I doubt anyone would want to run the cleanup 10 times per second or even more than 1 time per minute.

**Comment by hassox** [comment]
Good feedback. I've pushed up a v0.7.0 with these features :D
