### ISSUE TITLE
Missing guardian_db conf but the error is misleading  

### ISSUE THREAD

**Issue by jacktang** [ueberauth/guardian_db#24]
Hi

I missed `guardian_db` in config/config.exs and run `mix compile`, got below error:

```
== Compilation error on file lib/guardian_db.ex ==
** (FunctionClauseError) no function clause matching in Keyword.get/3
    (elixir) lib/keyword.ex:150: Keyword.get(nil, :schema_name, nil)
    lib/guardian_db.ex:25: (module)
    lib/guardian_db.ex:18: (module)

could not compile dependency :guardian_db, "mix compile" failed. You can recompile this dependency with "mix deps.compile guardian_db", update it with "mix deps.update guardian_db" or clean it with "mix deps.clean guardian_db"
```

According to [Keyword:get/3](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/keyword.ex#L150), the first arg should be `list` type, however [`Application.get_env(:guardian_db, GuardianDb)`](https://github.com/hassox/guardian_db/blob/master/lib/guardian_db.ex#L25) default value is nil. Further more, I really hope some humanized message like "Application conf guardian_db missed" pop out. 

BR
-Jack

**Comment by doomspork** [comment]
@jacktang pull requests are welcome!  Feel free to add in a more approachable error messages when configuration is not present.
