### ISSUE TITLE
Does not work fully  with MongoDB

### ISSUE THREAD

**Issue by dhonig** [ueberauth/guardian_db#25]
Writes are working fine with Mongo.   Reads fail to find the token.  Any interest in adding mongo support?

**Comment by kevinblade** [comment]
Hi!
I can't wait recover of this problem. So, I changed local deps as follows.
I'll waiting for cleared master release.

@moduledoc """
    A very simple model for storing tokens generated by guardian.
    """

```
use Ecto.Schema
# @primary_key {:jti, :string, autogenerate: false }
# primary key setting was changed as follow.
@primary_key {:id, :binary_id, autogenerate: true}
@schema_name Keyword.get(Application.get_env(:guardian_db, GuardianDb), :schema_name) || "guardian_tokens"
@schema_prefix Keyword.get(Application.get_env(:guardian_db, GuardianDb), :prefix) || nil

import Ecto.Changeset
import Ecto.Query

schema @schema_name do
  # jti field added for query in mongodb
  field :jti, :string
  field :typ, :string
  field :aud, :string
  field :iss, :string
  field :sub, :string
  field :exp, :integer
  field :jwt, :string
  field :claims, :map

  timestamps
end
```

**Comment by doomspork** [comment]
@dhonig a pull request that adds support is welcomed 😀

**Comment by kevinblade** [comment]
Since mongodb_ecto doesn't support timestamps in schema definition properly.
So, inserted_at, updated_at fields are not created in mongodb collection.
This issue is resolved with changing "use Ecto.Schema" to "use Ecto.Model"
You can reference this issue in [here](https://github.com/michalmuskala/mongodb_ecto/issues/62).

**Comment by dhonig** [comment]
@kevinblade Thats really cool to know.  We ended up chucking ecto on our project in favor of custom Mongo repositories.  In our case we were not getting enough from Ecto to stay with it due to different factors.  We wrote our own mongo guardian token store, which we will see if it can be opensourced for those not using ecto....
