### ISSUE TITLE
What is this compile error?

### ISSUE THREAD

**Issue by kevinblade** [ueberauth/guardian_db#28]
== Compilation error on file lib/guardian_db.ex ==
*\* (FunctionClauseError) no function clause matching in Keyword.get/3
    (elixir) lib/keyword.ex:150: Keyword.get(nil, :schema_name, nil)
    lib/guardian_db.ex:25: (module)
    lib/guardian_db.ex:18: (module)

**Comment by doomspork** [comment]
@kevinblade if we peek at [guardian_db.ex#L25](https://github.com/hassox/guardian_db/blob/master/lib/guardian_db.ex#L25) it looks like the application configuration is missing.  Can you double check that you've configured things correctly as per the README?
