### ISSUE TITLE
claims column - Not in use

### ISSUE THREAD

**Issue by ericsullivan** [ueberauth/guardian_db#3]
The claims column on guardian_tokens is not being populated with any data.

GuardianDb.repo.insert cast(%Token{}, prepared_claims, [], [:jti, :aud, :iss, :sub, :exp, :jwt])

Also, the permission "pem" claim is not stored in the database. I'm creating a UI for token creation and wanted to show the permissions (which I can get from the JWT), but I was wondering if the DB token was supposed to include the permissions. I could also add the pem field to the table if that's helpful.

**Comment by hassox** [comment]
Hmm... I think the claims should be encoded as a map (json). We can then include it in the case.

Thoughts?

**Comment by ericsullivan** [comment]
Sure, so pull out the fields which are already enumerated and put all of the claims into the claims field. I can work on that

**Comment by hassox** [comment]
I think it's still worthwhile having those fields that are already split out remain, storing the claims as json would be nice too :)
