### ISSUE TITLE
When 0.7.1(or more) would be released?

### ISSUE THREAD

**Issue by hykw** [ueberauth/guardian_db#38]
As the latest version, 0.7.0, depends to ecto 2.0.0-rc, those who use Phoenix cannot update phoenix_ecto from 3.0.1 to some latter versions...

**Comment by doomspork** [comment]
@hykw I can do that later today, just taking over maintenance of the GuardianDB library.  Need to get hex permissions and things sorted out.

**Comment by hykw** [comment]
Thank you!

**Comment by doomspork** [comment]
@hykw I would like to merge #42 and #37 then I will release a new version 👍

**Comment by imranismail** [comment]
yey finally, need to update some of the guide on api sign in as I just tried and there are regression errors

**Comment by krapans** [comment]
When this will be released?

**Comment by doomspork** [comment]
@artukrap you can use master until we cut a release:

```elixir
{:guardian_db, github: "ueberauth/guardian_db"}
```

**Comment by suhrawardi** [comment]
Thx! Works like a charm...! 😃

**Comment by doomspork** [comment]
@hykw / @suhrawardi / @imranismail / @artukrap — 0.8.0 release has been cut

**Comment by st23am** [comment]
@doomspork any word when hex can be updated?
