### ISSUE TITLE
Missing dependency in README.md

### ISSUE THREAD

**Issue by speeddragon** [ueberauth/guardian_db#49]
I was trying to create a API with guardian and guardian_db for authentication, and I was getting this error:

`** (Mix) Could not start application guardian_db: could not find application file: guardian_db.app`

After some minutes I notice that the dependency "guardian_db" wasn't on my `mix.exs` file. I've checked the README.me both on guardian and guardian_db and both doesn't state that I need to add this dependency (but I think it should be obvious).

I've checked the package in https://hex.pm/packages/guardian_db and added to `mix.exs`.

Anyway should this be on the README.md of this project ?

Thanks

**Comment by doomspork** [comment]
@speeddragon if you'd like to open a PR that amends the README to mention the dependency that would be fine 👍

**Comment by speeddragon** [comment]
Just notice that the PR from @egeersoz have that change, https://github.com/ueberauth/guardian_db/pull/48
