### ISSUE TITLE
schema_name config option ignored

### ISSUE THREAD

**Issue by davejlong** [ueberauth/guardian_db#55]
In my `config/config.exs`:

```elixir
config :guardian_db, GuardianDb,
  repo: CommunitiesOfHope.Repo,
  schema_name: "user_tokens",
```

And my migration:

```elixir
defmodule CommunitiesOfHope.Repo.Migrations.GuardianDb do
  use Ecto.Migration

  def change do
    create table(:user_tokens, primary_key: false) do
      add :jti, :string, primary_key: true
      add :aud, :string, primary_key: true
      add :typ, :string
      add :iss, :string
      add :sub, :string
      add :exp, :bigint
      add :jwt, :text
      add :claims, :map
      timestamps()
    end
  end
end
```

But when I try to login, I get the following error:

```
ERROR 42P01 (undefined_table): relation "guardian_tokens" does not exist
```

It seems that the `schema_name` config option is being ignored.

---

Elixir Version: 1.4.5
Erlang Version: 20
Dependency Versions:

```
$ mix deps | grep \* | sort
* bamboo 0.8.0 (Hex package) (mix)
* base64url 0.0.1 (Hex package) (rebar)
* bunt 0.2.0 (Hex package) (mix)
* certifi 1.2.1 (Hex package) (rebar3)
* comeonin 3.0.2 (Hex package) (mix)
* connection 1.0.4 (Hex package) (mix)
* cowboy 1.1.2 (Hex package) (rebar3)
* cowlib 1.0.2 (Hex package) (rebar3)
* credo 0.8.1 (Hex package) (mix)
* csvlixir 1.0.0 (Hex package) (mix)
* db_connection 1.1.2 (Hex package) (mix)
* decimal 1.3.1 (Hex package) (mix)
* ecto 2.1.4 (Hex package) (mix)
* elixir_make 0.4.0 (Hex package) (mix)
* ex_admin 0.9.0-dev (https://github.com/smpallen99/ex_admin.git) (mix)
* ex_queb 1.0.0 (Hex package) (mix)
* exactor 2.2.3 (Hex package) (mix)
* fs 0.9.1 (Hex package) (rebar)
* gettext 0.13.1 (Hex package) (mix)
* guardian 0.14.4 (Hex package) (mix)
* guardian_db 0.8.0 (Hex package) (mix)
* hackney 1.8.6 (Hex package) (rebar3)
* idna 5.0.2 (Hex package) (rebar3)
* inflex 1.8.1 (Hex package) (mix)
* jose 1.8.4 (Hex package) (mix)
* metrics 1.0.1 (Hex package) (rebar3)
* mime 1.1.0 (Hex package) (mix)
* mimerl 1.0.2 (Hex package) (rebar3)
* phoenix 1.2.4 (Hex package) (mix)
* phoenix_ecto 3.2.3 (Hex package) (mix)
* phoenix_html 2.9.3 (Hex package) (mix)
* phoenix_live_reload 1.0.8 (Hex package) (mix)
* phoenix_pubsub 1.0.2 (Hex package) (mix)
* plug 1.3.5 (Hex package) (mix)
* poison 2.2.0 (Hex package) (mix)
* poolboy 1.5.1 (Hex package) (rebar)
* postgrex 0.13.3 (Hex package) (mix)
* ranch 1.3.2 (Hex package) (rebar3)
* scrivener 2.3.0 (Hex package) (mix)
* scrivener_ecto 1.2.2 (Hex package) (mix)
* ssl_verify_fun 1.1.1 (Hex package) (rebar)
* ueberauth 0.4.0 (Hex package) (mix)
* ueberauth_identity 0.2.3 (Hex package) (mix)
* unicode_util_compat 0.2.0 (Hex package) (rebar3)
* uuid 1.1.7 (Hex package) (mix)
* xain 0.6.0 (Hex package) (mix)
```

**Comment by davejlong** [comment]
It seems that the error was because I had changed the `schema_name` value without recompiling the dependencies. I'll submit a PR to add a note about this to the documentation.

**Comment by yordis** [comment]
@davejlong the correct solution for this is to change https://github.com/ueberauth/guardian_db/blob/496384d0d42296bc69bdac1dac5dc17af830483d/lib/guardian_db.ex#L128

Talking to Michal about it, use module attributes for reading this configurations is a bad practice because of the situation you ran into, which is pretty common to run into

**Comment by yordis** [comment]
hhhhmmm I think I can't switch it to some function call 😢 so it will be better to actually add some documentation I think

**Comment by michalmuskala** [comment]
Ecto supports using `{"table_name", Schema}` as the source of a query. This can be leveraged by changing, for example:
https://github.com/ueberauth/guardian_db/blob/496384d0d42296bc69bdac1dac5dc17af830483d/lib/guardian_db.ex#L149
to
```elixir
GuardianDb.repo.get_by({token_source(), Token}, jti: jti, aud: aud)
```

It's also supported when creating structs like here:
https://github.com/ueberauth/guardian_db/blob/496384d0d42296bc69bdac1dac5dc17af830483d/lib/guardian_db.ex#L161-L163
which could be replaced by:
```elixir
%Token{}
|> Ecto.put_meta(source: token_source())
#...
```

Ecto makes sure that structs extracted from tagged queries when used with `update` or `delete` issue correct queries.

This should cover all the use cases.

**Comment by yordis** [comment]
@michalmuskala what is that `token_source` the `schema_name` in this case? What about the `schema "name over here"` situation?

Could you point me to the doc spot so I can read about it please

**Comment by michalmuskala** [comment]
`token_source` would be a function to load the table name, for example:

```elixir
defp token_source() do
  Application.fetch_env!(:guardian_db, GuardianDb)
  |> Keyword.get(:schema_name, "guardian_tokens")
end
```

This isn't documented anywhere in one place, unfortunately. Some bits are in the `Ecto.Schema` docs, some in `Ecto.Query` and some in `Ecto`. This would use the same technique as the one described in the [polymorphic belongs_to docs](https://hexdocs.pm/ecto/Ecto.Schema.html#belongs_to/3-polymorphic-associations).

**Comment by yordis** [comment]
@michalmuskala I notice this https://github.com/elixir-ecto/ecto/blob/v2.2.3/lib/ecto/schema.ex#L378 if I use `embedded_schema` I dont need any random name on the `schema` name because I will be using what you recommend.

What are your thoughts about it?

**Comment by michalmuskala** [comment]
`embedded_schema` generates a slightly different struct from `schema` - in particular, it doesn't track the lifetime of the struct (since it doesn't matter for embedded associations). The difference is the `__meta__` key.

**Comment by yordis** [comment]
@michalmuskala wouldn't be worth to add the differences in Ecto documentation?

Situation like this one people dont have to ask you what the differences are and it's important to know for apply the correct use of it.

For example right now, I don't know what you meant by `lifetime` of the struct and other situations.

What do you think?

**Comment by michalmuskala** [comment]
I opened a PR to ecto with improvements to the docs around the `__meta__` field: https://github.com/elixir-ecto/ecto/pull/2228

**Comment by yordis** [comment]
@michalmuskala you are the boss!
