### ISSUE TITLE
Error token_storage_failure

### ISSUE THREAD

**Issue by krapans** [ueberauth/guardian_db#67]
Went through installation guide, however, I got this error in the end when trying to do login.
![image](https://user-images.githubusercontent.com/11750685/30698445-a985587e-9eea-11e7-8746-38ed8709e09f.png)

**Comment by x-ji** [comment]
In case anybody runs into the same error in the future, in my case it is caused by a DB schema mismatch. If you use the default DB incremental ID as the `sub`, its type would be `:integer`, but the automatically generated migration has type `:string` by default, so you'd need to change the migration.

I think in this case the error message is really unhelpful. I had to look into the library and try to manually insert a valid token to find where the problem was.

**Comment by x-ji** [comment]
In fact even changing the migration doesn't help, since `GuardianDB` has hard-coded the `sub` to be of `string` type in its `Token` model. Maybe this is the standard for `sub` for all JWTs, but still, I find the error message very unhelpful.

**Comment by cultofmetatron** [comment]
but uh.. whats the solution??!!

**Comment by dershodan** [comment]
This error happened for me when i returned a non-string type in the implementation module's `subject_for_token` return tuple `{:ok, 10}`  for example.

The underlying error was for me:
```
#Ecto.Changeset<
  action: :insert,
  changes: %{
    aud: "my_app",
    claims: %{
      "aud" => "my_app",
      "claims" => %{
        "team_id" => 1,
        "user_id" => 1
      },
      "exp" => 1652277152,
      "iat" => 1649857952,
      "iss" => "my_app",
      "jti" => "cbc49b05-6c13-47be-84fc-00ab0ac2e725",
      "nbf" => 1649857951,
      "sub" => 10,
      "typ" => "access"
    },
    exp: 1652277152,
    iss: "my_app",
    jti: "cbc49b05-6c13-47be-84fc-00ab0ac2e725",
    jwt: "eyJhbGciOiJIUz............YBy9g6Q",
    typ: "access"
  },
  errors: [sub: {"is invalid", [type: :string, validation: :cast]}],
  data: #Guardian.DB.Token<>,
  valid?: false
>
```

I have to agree with @x-ji there - the error `:token_storage_failure` is not clear at all. It'd be probably better to at least serialize the `changeset.errors` and send that to the `Guardian.Plug.ErrorHandler.auth_error/3`

**Comment by yordis** [comment]
Feel free to open some PR improving the feature btw. Somebody tried to do it at some point but https://github.com/ueberauth/guardian_db/pull/120 didn't make it thru.

Feel free to pick up the work and address the problem with breaking changes and Guardian.
