### ISSUE TITLE
GuardianDB 1.0.0 version does not exist in Hex

### ISSUE THREAD

**Issue by Moussenger** [ueberauth/guardian_db#69]
Readme.md instructions say that version you must to set into dependecies is:

`{:guardian_db, "~> 1.0.0"}`

But in Hex does no exist that version (https://hex.pm/packages/guardian_db) and there is an error if you try running `mix deps.get`

> Running dependency resolution...
> 
>   Failed to use "guardian_db" because
>   mix.exs specifies ~> 1.0.0
> 
>   ** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or 
>    unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts 
>    you can try overriding with {:dependency, "~> 1.0", override: true}

**Comment by doomspork** [comment]
Thank you for letting me know @Moussenger!  I will work on getting a release cut 👍

**Comment by doomspork** [comment]
Sorry for the delays @Moussenger, we're working on getting in a few final features before officially cutting v1.0.  Once #73, #70, and #63 are merged this week we'll release.

Thanks for your patience 😁

**Comment by nikolay-slavov** [comment]
Hi there,
I'm experiencing a similar problem after adding `{:guardian_db, "~> 1.0.0"} `in my mix.exs file and then run `mix deps.get`.

> ** (Mix) No matching version for guardian_db ~> 1.0.0 (from: mix.exs) in registry

I guess this issue will be fixed when version 1.0.0 is officially released?

**Comment by yordis** [comment]
@nikolay-slavov getting there! No yet!

**Comment by 51stpage** [comment]
Looks published to me :smile: 
https://hex.pm/packages/guardian_db/1.0.0
