### ISSUE TITLE
Do you have any benchmark results as to what impact database verification has on performance?

### ISSUE THREAD

**Issue by acrolink** [ueberauth/guardian_db#75]
As measured by requests / second etc.. or response times as measured by milliseconds?

**Comment by yordis** [comment]
@acrolink I think this have more to do with how fast the database is than the package itself. That is potentially the bottleneck pretty much.

If performance is what matters for you then go with JWT without any database at all, one of the reason why they invented so you have the information that you need on the token and no needs to load anything from databases.

**Comment by doomspork** [comment]
Howdy @acrolink!  As @yordis mentioned, you don't _have_ to use GuardianDB though it is encouraged for security reasons.  At this time we don't have any benchmarking data but if you'd like to take a look into it, we'd be happy to put up the results 👍
