### ISSUE TITLE
Sweeper not working

### ISSUE THREAD

**Issue by acrolink** [ueberauth/guardian_db#77]
I still see the expired tokens in the database after they had expired, I expect them to be erased automatically after expiration. Any idea what to look for and check? Thank you.

**Comment by yordis** [comment]
@acrolink do you have any code example and or dataset I could use for replicate your issue?

Or you put the interval in a small fraction of time and put `IO.inspect` here https://github.com/ueberauth/guardian_db/blob/e338bdbe6e96dca028bee8e83bf78962ac1b41f1/lib/guardian/db/token/sweeper.ex#L12 on your `deps/guardian_db` so you can check it is being call

**Comment by acrolink** [comment]
I have reduced ttl and sweep interval to one minute, it is working. I will try to increase the ttl and sweep interval to see if it continues to work. I will report back.

**Comment by yordis** [comment]
@acrolink any updates on this one?

**Comment by acrolink** [comment]
Seems it is working.. I will watch for the expected behavior in regard to currently issued tokens in the next 4-5 hours and update.. Just to be sure..

**Comment by acrolink** [comment]
It is working as expected.
