### ISSUE TITLE
Warning when generating guardian db migration

### ISSUE THREAD

**Issue by ccarvalho-eng** [ueberauth/guardian_db#80]
Hello guys, 
Not sure if here's the right place to post this kind of stuff but let me know if not.
I followed the steps described on `README` but after run `mix guardian.db.gen.migration` I got this error:
```
** (Mix) The task "guardian.db.gen.migration" could not be found because the module is named Mix.Tasks.Guardian.DB.Gen.Migration instead of Mix.Tasks.Guardian.Db.Gen.Migration as expected. Please rename it and try again
```
Could someone, please, give me a help?

The error message is pretty simple to understand what's going on but I'd like to know if there's something I can do on my end or it is already being fixed.

**Comment by yordis** [comment]
@ueberauth/core  this is the 3rd issue related to this. It is fixed on `master`. Could you release this as soon as you can so we do not keep getting this issue please.

**Comment by ccarvalho-eng** [comment]
I think for now I can create the migration manually. Thanks

**Comment by yordis** [comment]
@webofbits sounds good, this is fixed on `master` but we need to release it.

**Comment by doomspork** [comment]
@yordis a guardian_db release?

**Comment by yordis** [comment]
@doomspork yes

**Comment by doomspork** [comment]
@yordis @webofbits `1.1.0` has been released 👍
