### ISSUE TITLE
(undefined_table): relation "virtual: token" does not exist

### ISSUE THREAD

**Issue by mrbegood** [ueberauth/guardian_db#82]
Hi, seems there is an error with ecto schema definition

https://github.com/ueberauth/guardian_db/blob/5e1a3df4c28f56ed71465583edf81b912bd6ac85/lib/guardian/db/token.ex#L15

guardian_db ~> 1.1

```
# mix guardian.db.gen.migration

defmodule MyApp.Repo.Migrations.Guardian.DB do
  use Ecto.Migration

  def change do
    create table(:guardian_tokens, primary_key: false) do
      add(:jti, :string, primary_key: true)
      add(:aud, :string, primary_key: true)
      add(:typ, :string)
      add(:iss, :string)
      add(:sub, :string)
      add(:exp, :bigint)
      add(:jwt, :text)
      add(:claims, :map)
      timestamps()
    end
  end
end
```

```
iex(1)> MyApp.Repo.all(Guardian.DB.Token)
[debug] QUERY ERROR source="virtual: token" db=10.2ms
SELECT v0."jti", v0."typ", v0."aud", v0."iss", v0."sub", v0."exp", v0."jwt", v0."claims", v0."inserted_at", v0."updated_at" FROM "virtual: token" AS v0 []
** (Postgrex.Error) ERROR 42P01 (undefined_table): relation "virtual: token" does not exist
    (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
```

**Comment by doomspork** [comment]
@mrbegood what version of Ecto are you using?

**Comment by yordis** [comment]
@doomspork this is not an issue.

He is using `MyApp.Repo.all(Guardian.DB.Token)` directly which he is not aware of the table being an virtual table.

This is the reason why this exists https://github.com/ueberauth/guardian_db/blob/5e1a3df4c28f56ed71465583edf81b912bd6ac85/lib/guardian/db/token.ex#L64

And you would use it this way https://github.com/ueberauth/guardian_db/blob/5e1a3df4c28f56ed71465583edf81b912bd6ac85/lib/guardian/db/token.ex#L34

@mrbegood You need to use ` Guardian.DB.repo().all(Guardian.DB.Token.query_schema())` if I am not mistaking.

Or I would suggest to create your own schema for this, sometimes a copy and paste is the solution.

**Comment by yordis** [comment]
More details about Ecto usage, https://github.com/ueberauth/guardian_db/issues/55#issuecomment-329082925

**Comment by mrbegood** [comment]
@yordis thanks for your answer
this solution `Guardian.DB.repo().all(Guardian.DB.Token.query_schema())` works as I need!!!
