### ISSUE TITLE
Tokens are not revoked

### ISSUE THREAD

**Issue by bcat-eu** [ueberauth/guardian_db#88]
My `on_revoke` callback just rests there and is never called when user is signed out (Guardian's `sign_out` is called). I ended up switching to before_sign_out callback to get the logouts working:

```
  def before_sign_out(conn, location, _options) do
    claims = __MODULE__.Plug.current_claims(conn, key: location)
    token = __MODULE__.Plug.current_token(conn, key: location)

    if claims && token do
      with {:ok, _} <- Guardian.DB.on_revoke(claims, token) do
        {:ok, conn}
      end
    end

    {:ok, conn}
  end
```

This might be a Guardian issue since they state that sign_out will "remove from session (if fetched) and revoke the token", but in any case the current setup as described in readme doesn't seem to work.

Also as mentioned in #87 `on_refresh` callback as described triggers warning, there is really no such function yet (it is in the repository but is not released).

**Comment by yordis** [comment]
@bcat-eu could you try to use `master` and see if the issue persists? `on_refresh` does exists if you take a look to the code.

**Comment by bcat-eu** [comment]
@yordis I've checked the `on_revoke` with master and it does work there :+1: 

Is there a reason not to release right away? Current behavior is confusing since if all is done as stated in the readme then each login generates a token and logout doesn't delete it which is only noticeable via explicit tests. 

Anyway since the issue is resolved in master the ticket can be closed now, thanks!
