### ISSUE TITLE
function Guardian.DB.on_refresh/2 is undefined or private

### ISSUE THREAD

**Issue by tanweerdev** [ueberauth/guardian_db#91]
Steps to reproduce:
Add hex dependency of `guardian_db` plus configurations and when project will be compiled, you will get this error.
Please release a new version. This will be fixed as we already have this fixed in current codebase

**Comment by egeersoz** [comment]
Any updates on this issue?

**Comment by yordis** [comment]
@egeersoz it will get release the next week.

**Comment by doomspork** [comment]
If you need to use this before a new release is cut you can always point to master in mix:

```elixir
{:guardian_db, github: "ueberauth/guardian_db"}
```
